version: 2

updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: monthly
    groups:
      github-actions:
        patterns:
          - "*"

  - package-ecosystem: swift
    directory: /OpenKeyboardCore
    schedule:
      interval: monthly
    allow:
      - dependency-name: "*"
        update-types:
          - "version-update:semver-patch"
          - "version-update:semver-minor"
    groups:
      swift-dependencies:
        patterns:
          - "*"
